Added '/update_whitelist' command.
SimulatorML/SpamKiller pull request #12
Opened 2024-02-02 19:04 UTC by maltsevd

2024-02-05 19:42 UTC, sokolgood requested changes
небольшие моменты поправить, а так отлично, спасибо!

2024-02-05 19:42 UTC, sokolgood commented on src/app/loader.py
> +from utils.scrapper import Scrapper
src.utils.scrapper будет лучше

2024-02-05 19:42 UTC, sokolgood commented on src/utils/commands.py
> +    channel = f'@{message.get_args().strip()}'
Нужно добавить возможность указания количества сообщений, которое нужно парсить (то есть N), а также после какого сообщения юзера считать не спам (n в данном случае)

А также нужно учесть, что пользователь может что-то неправильно ввести. Сделать простенькую валидацию параметров

2024-02-05 19:42 UTC, sokolgood commented on src/utils/commands.py
> +    with open(path_whitelist_users, 'a') as file:
можно было сделать за одно открытие файла, но не критично

2024-02-05 19:42 UTC, sokolgood commented on src/utils/scrapper.py
> +    def __init__(self, api_id: int = API_ID, api_hash: str = API_HASH, N: int = 10000, n: int = 3):
Не совсем понятно за что отвечают N и n. Лучше сделать более понятные названия переменных, ну либо написать пояснение за что отвечают параметры

2024-02-06 12:37 UTC, maltsevd commented on src/app/loader.py
> +from utils.scrapper import Scrapper
Готово

2024-02-06 12:39 UTC, maltsevd commented on src/utils/commands.py
> +    channel = f'@{message.get_args().strip()}'
Реализовал варианты с указанием количества или же с дефолтными значениями из конфига. Валидация по типу вводимых аргументов и на их положительные значения

2024-02-06 12:39 UTC, maltsevd commented on src/utils/commands.py
> +    with open(path_whitelist_users, 'a') as file:
Готово

2024-02-06 12:40 UTC, maltsevd commented on src/utils/scrapper.py
> +    def __init__(self, api_id: int = API_ID, api_hash: str = API_HASH, N: int = 10000, n: int = 3):
Изменил названия на depth и threshold

2024-02-06 13:10 UTC, mayb333 approved these changes
Все классно, спасибо!

2024-02-06 13:11 UTC, merged